-- MySQL Script generated by MySQL Workbench
-- Sun Nov 29 00:49:47 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CrediteService
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CrediteService
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CrediteService` DEFAULT CHARACTER SET utf8 ;
USE `CrediteService` ;

-- -----------------------------------------------------
-- Table `CrediteService`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CrediteService`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CrediteService`.`bank`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CrediteService`.`bank` (
  `idbank` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `budget` INT NULL,
  PRIMARY KEY (`idbank`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CrediteService`.`credit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CrediteService`.`credit` (
  `idcredit` INT NOT NULL,
  `startDate` DATETIME NOT NULL,
  `finishDate` DATETIME NOT NULL,
  `sum` INT NULL,
  `percent` INT NOT NULL,
  `status` ENUM('opened', 'closed') NOT NULL,
  `user_iduser` INT NOT NULL,
  `bank_idbank` INT NOT NULL,
  PRIMARY KEY (`idcredit`),
  INDEX `fk_credit_user1_idx` (`user_iduser` ASC) VISIBLE,
  INDEX `fk_credit_bank1_idx` (`bank_idbank` ASC) VISIBLE,
  CONSTRAINT `fk_credit_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `CrediteService`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_credit_bank1`
    FOREIGN KEY (`bank_idbank`)
    REFERENCES `CrediteService`.`bank` (`idbank`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
